Sube2.HelloMvc/Controllers/DersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube2.HelloMvc.Models;
using Sube2.HelloMvc.Models.Relationships;

namespace Sube2.HelloMvc.Controllers
{
    public class DersController : Controller
    {
        public IActionResult Index()
        {
            using (var ctx = new OkulDbContext())
            {
                var lst = ctx.Dersler.ToList();
                return View(lst);
            }
        }

        [HttpGet]
        public IActionResult AddDers()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddDers(Ders ders)
        {
            if (ders != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Dersler.Add(ders);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult EditDers(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ders = ctx.Dersler.Find(id);
                return View(ders);
            }
        }

        [HttpPost]
        public IActionResult EditDers(Ders ders)
        {
            if (ders != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Entry(ders).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult DeleteDers(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ders = ctx.Dersler.Find(id);
                if (ders != null)
                {
                    ctx.Dersler.Remove(ders);
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        public IActionResult KayitliOgrenciler(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ders = ctx.Dersler.Include(d => d.OgrenciDersler!).ThenInclude(od => od.Ogrenci!).FirstOrDefault(d => d.Dersid == id);
                if (ders == null)
                {
                    return NotFound();
                }

                if (ders.OgrenciDersler == null)
                {
                    ders.OgrenciDersler = new List<OgrenciDers>();
                }

                return View(ders);
            }
        }
    }
}

Sube2.HelloMvc/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using Sube2.HelloMvc.Models;


namespace Sube2.HelloMvc.Controllers
{
    public class OgrenciController : Controller
    {
        public ViewResult Index()  //Action
        {
            return View();
        }

        public ViewResult OgrenciDetay(int id)
        {
            //Ogretmen ogrt = null;
            //Models.Ogrenci ogr = null;
            //Ders ds = null;
            //if (id == 1) 
            //{
            //    ogr= new Models.Ogrenci();
            //    ogr.Ad = "Ali";
            //    ogr.Soyad = "Veli";
            //    ogr.Numara = 123;

            //    ogrt = new Ogretmen();
            //    ogrt.Ad = "Ali Berkay";
            //    ogrt.Soyad = "CAN";
            //    ogrt.OgretmenId = 1;

            //    ds = new Ders();
            //    ds.kredi = 5;
            //    ds.DersId = 1;
            //    ds.DersAd = "Programlama";
            //}
            //else if (id == 2) 
            //{
            //    ogr = new Models.Ogrenci { Ad = "Ahmet", Soyad = "Mehmet", Numara = 123 };
            //}

            ////var model = Tuple.Create(ogr, ogrt);

            //ViewData["school"] = ogr;
            //ViewBag.student = ogr;
            //ViewBag.ogretmen = ogrt;

            //OkulViewModels vm = new OkulViewModels();
            //vm.ogretmen = ogrt;
            //vm.ogrenci = ogr;
            //vm.ders = ds;
            return View();
        }

        public ViewResult OgrenciListe()
        {
            //var lst = new List<Models.Ogrenci> { 
            //new Models.Ogrenci { Ad = "Mert", Soyad = "Mehmet", Numara = 1 },
            //new Models.Ogrenci { Ad = "Selim", Soyad = "Okan", Numara = 2 }
            //};

            return View();
        }
    }
}


















//Controller->View veri taşıma
//ViewData:Bir koleksiyon yapısıdır. ViewData bir dictionary yapısıdır. Anahtar ve değer çiftlerinden oluşur.

//ViewBag: Arka planda ViewData koleksiyonunu kullanan,dynamic yapıda bir veri taşıma yapısıdır.

//ViewModel

Sube2.HelloMvc/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Sube2.HelloMvc.Models;
using Sube2.HelloMvc.Models.Relationships;

namespace Sube2.HelloMvc.Controllers
{
    public class StudentController : Controller
    {
        public IActionResult Index()
        {
            using (var ctx = new OkulDbContext())
            {
                var lst = ctx.Ogrenciler.ToList();
                return View(lst);
            }
        }

        public IActionResult AddStudent() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddStudent(Ogrenci ogr)
        { 
            if(ogr != null)
            {
                using (var ctx = new OkulDbContext()) 
                {
                    ctx.Ogrenciler.Add(ogr);
                    ctx.SaveChanges();
                }
                    
            }
            return RedirectToAction("Index");
        }
        public IActionResult EditStudent(int id) 
        {
            using (var ctx = new OkulDbContext())
            {
                var ogr = ctx.Ogrenciler.Find(id);
                return View(ogr);
            }
        }
        [HttpPost]
        public IActionResult EditStudent(Ogrenci ogr)
        {
            if (ogr != null)
            {
                using (var ctx = new OkulDbContext())
                {
                    ctx.Entry(ogr).State = EntityState.Modified; 
                    ctx.SaveChanges();
                }
            }
            return RedirectToAction("Index");   
        }
        public IActionResult DeleteStudent(int id) 
        {

            using (var ctx = new OkulDbContext()) 
            {
                ctx.Ogrenciler.Remove(ctx.Ogrenciler.Find(id));
                ctx.SaveChanges();
            }   
            return RedirectToAction("Index");
        }
        
        public IActionResult OgrenciDersleri(int id)
        {
            using (var ctx = new OkulDbContext())
            {
                var ogrenci = ctx.Ogrenciler.Include(o => o.OgrenciDersler!).ThenInclude(od => od.Ders).FirstOrDefault(o => o.Ogrenciid == id);

                return View(ogrenci);
            }
        }

        [HttpGet]
        public IActionResult AddDersForOgrenci(int studentId)
        {
            using (var ctx = new OkulDbContext())
            {
                var dersler = ctx.Dersler.ToList();
                var ogrenciDersler = ctx.OgrenciDersler.Where(od => od.Ogrenciid == studentId).Select(od => od.Dersid).ToList();
                var AktifDersler = dersler.Where(d => !ogrenciDersler.Contains(d.Dersid)).ToList();

                ViewBag.StudentId = studentId;
                return View(AktifDersler);
            }
        }


        [HttpPost]
        public IActionResult AddDersForOgrenci(int studentId, List<int> dersIds)
        {
            using (var ctx = new OkulDbContext())
            {
                var mevcutDersId = ctx.OgrenciDersler.Where(od => od.Ogrenciid == studentId).Select(od => od.Dersid).ToList();
                var yeniDersId = dersIds.Except(mevcutDersId).ToList();

                foreach (var dersId in yeniDersId)
                {
                    var ogrenciDers = new OgrenciDers
                    {
                        Ogrenciid = studentId,
                        Dersid = dersId
                    };
                    ctx.OgrenciDersler.Add(ogrenciDers);
                }
                ctx.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}
    

Sube2.HelloMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sube2.HelloMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sube2.HelloMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-info border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ali Berkay CAN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-action="Index" asp-controller="Student">Öğrenci İşlemleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-action="Index" asp-controller="Ders">Ders İşlemleri</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="">
        <div class="container-fluid text-center text-white p-3 mt-2 fixed-bottom" style="background-color:#009354;">
    <h5>Ali Berkay Can Tarafindan Tasarlandi & Gelistirildi</h5>		
</div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
@*
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Ogrenci/OgrenciListe">Öğrenci Listesi</a>
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Öğreni Listesi", "OgrenciListe", "Ogrenci", null, new { @class = "nav-link text-dark" })
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="OgrenciListe" asp-controller="Ogrenci">Öğrenci Listesi</a>
                        </li>
                        *@